USE [master]
GO

/****** Object:  Database [MoviiumDB]    Script Date: 22.10.2020. 14:39:40 ******/
CREATE DATABASE [MoviiumDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MoviiumDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MoviiumDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MoviiumDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MoviiumDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MoviiumDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MoviiumDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MoviiumDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MoviiumDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MoviiumDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MoviiumDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MoviiumDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MoviiumDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MoviiumDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MoviiumDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MoviiumDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MoviiumDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MoviiumDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MoviiumDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MoviiumDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MoviiumDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MoviiumDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MoviiumDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MoviiumDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MoviiumDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MoviiumDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MoviiumDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MoviiumDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MoviiumDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MoviiumDB] SET  MULTI_USER 
GO

ALTER DATABASE [MoviiumDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MoviiumDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MoviiumDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MoviiumDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MoviiumDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MoviiumDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MoviiumDB] SET  READ_WRITE 
GO

